name: Deploy Dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Build the Docker image
      run: docker-compose build

    - name: Deploy
      run: docker-compose up -d --remove-orphans
